### ISSUE TITLE
Preprocessing scripts and process

### ISSUE THREAD

**Issue by swethmandava** [arwhirang/recursive_chemprot#2]
How was the data preprocessed to produce https://github.com/arwhirang/recursive_chemprot/tree/master/Demo/tree_LSTM/data ? Are the scripts available? Thank you!

**Comment by arwhirang** [comment]
Hello,

The thing is, I didn't make scripts for preprocessing. Due to the constant change in code, managing a script was a hassle. However, I can give you the most important preprocessing part - parsing. 
As described in the paper, the preprocess part consists of "small preprocessing before parsing" and "parsing + feature generation". 
e.g.
(first part)
16970975	In defects of BC6ENTG , BC6OTHER is transformed to BC6ENTC , resulting in high levels of BC6OTHER in the body.	False		T33	AGAT	T10	oxalate
(second part)
16970975	In defects of BC6ENTG , BC6OTHER is transformed to BC6ENTC , resulting in high levels of BC6OTHER in the body.	False		T33	AGAT	T10	oxalate	(0/0/0/0 (0/0 (0/1 In) (0/0 (0/1 defects) (0/0 (0/1 of) (0/0 BC6ENTG)))) (0/0 (0/1 ,) (0/0 (0/1 BC6OTHER) (0/0 (0/0 (0/1 is) (0/0 (0/0 (0/0 (0/1 transformed) (0/0 (0/1 to) (0/0 BC6ENTC))) (0/1 ,)) (0/1 (0/1 resulting) (0/1 (0/1 in) (0/1 (0/1 (0/1 (0/1 high) (0/1 levels)) (0/1 (0/1 of) (0/1 BC6OTHER))) (0/1 (0/1 in) (0/1 (0/1 the) (0/1 body)))))))) (0/1 .)))))	In, defects, of, BC6ENTG, ,, BC6OTHER, is, transformed, to, BC6ENTC, ,, resulting, in, high, levels, of, BC6OTHER, in, the, body, .

The attached file is the code for the second part. Although it is quite dirty for generating features, if you ignore the feature generation part, it would be easy to understand. The code is written in JAVA to run the stanford parser. Hope it helps.
[Parse_verRecurBC6.zip](https://github.com/arwhirang/recursive_chemprot/files/3844320/Parse_verRecurBC6.zip)

**Comment by swethmandava** [comment]
Thanks @arwhirang !

I'm most interested in the parsing part and I'm having trouble understanding the dataset.

For example, for a particular sentence, there might be 4 entities: T1(chemical), T2(chemical), T3(gene) & T4(gene). and three relations, T1-T3, T2-T4.

I preprocessed this to form two sentences for training. One with T1 and T3 replaced to token words (CHEMICAL/GENE) and the other with T2 and T4 replaced while keeping the others unchanged.

However, looking at your dataset, it looks like all the 4 tokens are replaced by their token words and 4 sentences are created, accounting for T1-T4 and T2-T3 with labels set to False. Is that intentional? It is then hard to understand which two tokens specifically we are getting relations between and the same sentence might end up having multiple different ground truth labels.

**Comment by arwhirang** [comment]
It would be better if you could tell me the instance number and the target entities.

(Actually, the anonymization techinque is different from spinn version and the tree-lstm version. Since the spinn-version implementation performs better, I explain below the anonymization used in the spinn-version.)

Each instance represents one relationship.

e.g.
Let's suppose there are 4 entities in a sentence and 2 true relations exist between entities. (true case: T1-T3, T2-T4)
We anonymized the sentence and made up to 6 instances. (T1-T2, T1-T3, T1-T4, T2-T3, T2-T4, T3-T4) Of course, Chemical-Chemical relation or Gene-Gene relation is discarded. Therefore, each instance has 2 target entities and 2 other entities. We replaced the other entities as "BC6OTHER" to disregard the relation that encompass any "BC6OTHER" entities.
